CREATE SEQUENCE  ESQ_IOTRAMITE.NU_INT_ANX  INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;
CREATE SEQUENCE  ESQ_IOTRAMITE.NU_INT_DES_EXT  INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;
CREATE SEQUENCE  ESQ_IOTRAMITE.NU_INT_DOC_EXT  INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;
CREATE SEQUENCE  ESQ_IOTRAMITE.NU_INT_DOC_PRI  INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;
CREATE SEQUENCE  ESQ_IOTRAMITE.NU_INT_DOC_REC  INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;

/* TABLAS INTEROPERABILIDAD */

CREATE TABLE ESQ_IOTRAMITE.IOTDTC_RECEPCION (
                SIDRECEXT smallint DEFAULT nextval('ESQ_IOTRAMITE.NU_INT_DOC_REC'::regclass) NOT NULL ,
                VRUCENTREM VARCHAR(11) NOT NULL,
                VUNIORGREM VARCHAR(250) NOT NULL,
                CTIPDOCIDEREM CHAR(1) NOT NULL,
                VNUMDOCIDEREM VARCHAR(9) NOT NULL,
                VNUMREGSTD VARCHAR(14),
                VANIOREGSTD VARCHAR(4),
                VUNIORGSTD VARCHAR(250),
                CCODUNIORGSTD CHAR(15),
				VDESANXSTD VARCHAR(750),
                DFECREGSTD TIMESTAMPTZ,
                VUSUREGSTD VARCHAR(100),
                BCARSTD BYTEA,
                VCUO VARCHAR(10) NOT NULL,
                VCUOREF VARCHAR(10),
                VOBS VARCHAR(250),
                CFLGEST CHAR(1) NOT NULL,
                VUSUMOD VARCHAR(15),
                DFECMOD DATE,
                CFLGESTOBS CHAR(1) DEFAULT 'N',
                CFLGENVCAR CHAR(1) DEFAULT 'N',
				CFLGANU CHAR(1) DEFAULT 'N',
                DFECREG TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                CONSTRAINT PK_RECEPCION PRIMARY KEY (SIDRECEXT),
                CONSTRAINT UNIQUE_VCUO_RECEPCION UNIQUE (VCUO),
                CONSTRAINT UNIQUE_VNUMREGSTD_RECEPCION UNIQUE (VNUMREGSTD)
);
COMMENT ON COLUMN ESQ_IOTRAMITE.IOTDTC_RECEPCION.CTIPDOCIDEREM IS 'CODIGO DE TIPO DE DOCUMENTO DE IDENTIDAD 1 = DNI, 2 = CARNET DE EXTRANJERIA';


CREATE TABLE ESQ_IOTRAMITE.IOTDTC_DESPACHO (
                SIDEMIEXT SMALLINT DEFAULT nextval('ESQ_IOTRAMITE.NU_INT_DES_EXT'::regclass) NOT NULL ,
                VNUMREGSTD VARCHAR(14),
                VANIOREGSTD VARCHAR(4),
                CTIPDOCIDEREM CHAR(1) NOT NULL,
                VNUMDOCIDEREM VARCHAR(9) NOT NULL,
                VCODUNIORGREM VARCHAR(15),
                VUNIORGREM VARCHAR(250),
                VCUO VARCHAR(10),
                VRUCENTREC VARCHAR(11) NOT NULL,
                VNOMENTREC VARCHAR(200) NOT NULL,
                VNUMREGSTDREC VARCHAR(14),
                VANIOREGSTDREC VARCHAR(4),
				VUNIORGSTDREC VARCHAR(250),
				VDESANXSTDREC VARCHAR(750),
                DFECREGSTDREC TIMESTAMPTZ,
                VUSUREGSTDREC VARCHAR(150),
                BCARSTDREC BYTEA,
                VOBS VARCHAR(250),
                VCUOREF VARCHAR(10),
                CFLGEST CHAR(1) DEFAULT 'P'  NOT NULL,
                CFLGENV CHAR(1) DEFAULT 'N' NOT NULL,
                DFECENV TIMESTAMPTZ,
                VUSUREG VARCHAR(15) NOT NULL,
                DFECREG TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                VUSUMOD VARCHAR(15),
                DFECMOD DATE,
                CONSTRAINT PK_DESPACHO PRIMARY KEY (SIDEMIEXT),
                CONSTRAINT UNIQUE_VUO_DESPACHO UNIQUE (VCUO),
                CONSTRAINT UNIQUE_VNUMREGSTD_DESPACHO UNIQUE (VNUMREGSTD)
);
COMMENT ON COLUMN ESQ_IOTRAMITE.IOTDTC_DESPACHO.CFLGENV IS 'FLAG QUE INDICA LA CONFIRMACION DE QUE EL DOCUMENTO FUE ENVIADO N = NO SE PRODUJO INTENTO DE ENVIO, E = ERROR EN EL ENVIO';


CREATE TABLE ESQ_IOTRAMITE.IOTDTM_DOC_EXTERNO (
                SIDDOCEXT SMALLINT DEFAULT nextval('ESQ_IOTRAMITE.NU_INT_DOC_EXT'::regclass) NOT NULL ,
                VNOMENTEMI VARCHAR(250) NOT NULL,
                CCODTIPDOC CHAR(2) NOT NULL,
                VNUMDOC VARCHAR(100) NOT NULL,
                DFECDOC TIMESTAMPTZ NOT NULL,
                VUNIORGDST VARCHAR(150) NOT NULL,
                VNOMDST VARCHAR(100) NOT NULL,
                VNOMCARDST VARCHAR(100) NOT NULL,
                VASU VARCHAR(500) NOT NULL,
                CINDTUP CHAR(1) DEFAULT 'N',
                SNUMANX SMALLINT DEFAULT 0,
                SNUMFOL SMALLINT DEFAULT 0  NOT NULL,
                VURLDOCANX VARCHAR(200),
                SIDEMIEXT SMALLINT,
                SIDRECEXT SMALLINT,
                CONSTRAINT PK_DOC_EXTERNO PRIMARY KEY (SIDDOCEXT)
);


CREATE TABLE ESQ_IOTRAMITE.IOTDTD_DOC_PRINCIPAL (
                SIDDOCPRI SMALLINT DEFAULT nextval('ESQ_IOTRAMITE.NU_INT_DOC_PRI'::regclass) NOT NULL ,
                SIDDOCEXT SMALLINT NOT NULL,
                VNOMDOC VARCHAR(200) NOT NULL,
                BPDFDOC BYTEA NOT NULL,
                DFECREG TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                CONSTRAINT PK_DOC_PRINCIPAL PRIMARY KEY (SIDDOCPRI)
);


CREATE TABLE ESQ_IOTRAMITE.IOTDTD_ANEXO (
                SIDDOCANX SMALLINT DEFAULT nextval('ESQ_IOTRAMITE.NU_INT_ANX'::regclass) NOT NULL ,
                VNOMDOC VARCHAR(100) NOT NULL,
                DFECREG TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                SIDDOCEXT SMALLINT NOT NULL,
                CONSTRAINT PK_ANEXO PRIMARY KEY (SIDDOCANX)
);


ALTER TABLE ESQ_IOTRAMITE.IOTDTM_DOC_EXTERNO ADD CONSTRAINT RECEPCION_FK_DOC_EXTERNO
FOREIGN KEY (SIDRECEXT)
REFERENCES ESQ_IOTRAMITE.IOTDTC_RECEPCION (SIDRECEXT)
NOT DEFERRABLE;

ALTER TABLE ESQ_IOTRAMITE.IOTDTM_DOC_EXTERNO ADD CONSTRAINT DESPACHO_FK_DOC_EXTERNO
FOREIGN KEY (SIDEMIEXT)
REFERENCES ESQ_IOTRAMITE.IOTDTC_DESPACHO (SIDEMIEXT)
NOT DEFERRABLE;

ALTER TABLE ESQ_IOTRAMITE.IOTDTD_ANEXO ADD CONSTRAINT TDTM_DOC_EXTERNO_TDTD_ANEXO_FK
FOREIGN KEY (SIDDOCEXT)
REFERENCES ESQ_IOTRAMITE.IOTDTM_DOC_EXTERNO (SIDDOCEXT)
NOT DEFERRABLE;

ALTER TABLE ESQ_IOTRAMITE.IOTDTD_DOC_PRINCIPAL ADD CONSTRAINT IOTDTM_DOC_EXTERNO_IOTDTD_D711
FOREIGN KEY (SIDDOCEXT)
REFERENCES ESQ_IOTRAMITE.IOTDTM_DOC_EXTERNO (SIDDOCEXT)
NOT DEFERRABLE;
